name: chatty
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # App Write Database (For dynamically getting API Key)  
  appwrite: ^12.0.4
  # appwrite: 
  #   path: ./appwrite

  # iOS Styled Icons
  cupertino_icons: ^1.0.8

  # For using Lottie Animations
  lottie: ^3.1.2

  # For Hive Database
  # hive: ^4.0.0-dev.2
  # isar_flutter_libs: ^4.0.0-dev.13

  # Using this version due to less apk size
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For Accessing Storage Path
  path_provider: ^2.1.3

  # For State Management
  get: ^4.6.6


  # For Custom Animation
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2

  # For API Call
  http: ^1.2.2

  # For AI Image Generation
  dart_openai: ^5.1.0
  cached_network_image: ^3.3.1
  
  # Google Gemini Ai Integration
  google_generative_ai: ^0.4.3

  # For Google Language Translate
  translator_plus: ^1.0.1

  # For Saving Image to Gallery
  image_gallery_saver: ^2.0.3

  # For Sharing Image
  share_plus: ^9.0.0

  # Facebook Ads
  easy_audience_network: ^0.0.6

  # Add your preferred ML kit or AI API packages
  google_ml_kit: ^0.13.0


  # For Voice Features
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  image_picker: ^1.0.7

  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Encourages Good Practices
  flutter_lints: ^4.0.0

  # For Changing App Icon
  # icons_launcher: ^2.1.7

flutter:

  # Enables Material Design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/rive/
    - assets/images/
    - assets/lottie/
    - assets/lottie/image_scan.json
    - assets/lottie/translate.json
    - assets/lottie/face_scan.json
    - assets/lottie/text_scan.json